sandialabs/qthreads

config/qthread_check_hwloc.m4
=> Fixes typo.

.gitlab-ci.yml, src/affinity/mach.c
These changes contain a bug fix for #7 and a new yml file for GitLab automated testing support.
=> Bugfix and testing file

src/syncvar.c
=> fix issue #8: Error in comment

NEWS, src/affinity/binders.c, src/affinity/hwloc.c, src/affinity/hwloc_v2.c, src/affinity/hwloc_via_chapel.c
Improvements:
- Add support for Spack testing (spack test run qthreads)
- Add support for hwloc2.x (minimal required version is hwloc1.5)
Documentation:
- User guide for basic Qthreads usage (see userguide subdirectory for LaTex and included code source files)
=> Release 1.16 rc

.github/workflows/CI.yml, src/affinity/binders.c
Add a missing qt_alloc include to the binders topology layer. Also adds
CI testing for binders.
=> Fix the binders topology layer

include/qt_blocking_structs.h, src/io.c, src/syscalls/accept.c, src/syscalls/connect.c, src/syscalls/poll.c, src/syscalls/pread.c, src/syscalls/pwrite.c, src/syscalls/read.c, src/syscalls/select.c, src/syscalls/system.c, src/syscalls/wait4.c, src/syscalls/write.c
Fixes issue that errno is not preserved following qt system calls.
=> Syscall fix errno

include/qt_blocking_structs.h, include/qt_debug.h, src/hashmap.c, src/patterns/wavefront.c, src/qloop.c, src/shepherds.c, src/syscalls/pread.c, src/syscalls/pwrite.c, src/syscalls/read.c, src/syscalls/write.c, src/threadqueues/lifo_threadqueues.c, src/threadqueues/mutexfifo_threadqueues.c, src/threadqueues/nemesis_threadqueues.c, src/threadqueues/nottingham_threadqueues.c, src/threadqueues/sherwood_threadqueues.c
Co-authored-by: Michael Ferguson <mppf@users.noreply.github.com>
Co-authored-by: Jan Ciesko <jan.ciesko@gmail.com>
=> Add missing include #include <sys/types.h> to support ssize

include/qthread/qthread.h
- Improves version format and updates version number to current.
(I would prefer a version file (version.in) and a version.h header where configure sets a string. This would give a cleaner version history. We can do that someday. )
=> Improve version format and update version number

scripts/package.sh
- Adds separators
- Replaces -j option with -z (bzip2 vs gzip)
=> Improve distrib gen script

test/basics/qthread_stackleft.c
Addresses https://github.com/Qthreads/qthreads/issues/126
=> Remove static qualifier from stack_left test

config/qthread_check_hwloc.m4
By default, `configure` tests `hwloc` linking against a static list of potential link-time arguments. This commit makes the check optional to avoid having to maintain the static list. The `--disable-hwloc-configure-checks` argument turns off the `hwloc` link check. The link check also tests whether or not `hwloc` supports distance information. If the link check is disabled, `configure` assumes that `hwloc` supports distance information. This may be changed by passing` --disable-hwloc-has-distance` to `configure`.
=> Make config-time check of hwloc linking optional

Makefile.am, configure.ac, qthread.pc.in
Largely based on hwloc's and https://lists.freedesktop.org/archives/pkg-config/2007-August/000219.html
Resolves #107
=> Add pkg-config support

.circleci/config.yml, config/qthread_check_makecontext.m4
Currently just testing in CI to check whether https://github.com/sandialabs/qthreads/issues/160 is easy to fix or not. I'll mark this as ready and request review if the fix does end up being simple.
Depends on https://github.com/sandialabs/qthreads/pull/170.
=> Debugging MUSL Libc

test/basics/external_syncvar.c
=> Fix Thread Leak In `external_syncva` Test

.circleci/config.yml, .github/workflows/CI.yml, include/qt_addrstat.h, include/qthread/allpairs.h, src/ds/dictionary/hash.c, src/ds/qarray.c, src/patterns/allpairs.c, src/qloop.c, src/qutil.c, src/threadqueues/nemesis_threadqueues.c, test/basics/aligned_writeFF_basic.c, test/basics/qthread_fp_double.c, test/basics/qtimer.c, test/basics/sinc_workers.c, test/basics/test_teams.c, test/features/allpairs.c, test/features/qloop_utils.c, test/features/qutil.c, test/stress/lock_acq_rel.c, test/utils/rng/Makefile.am, test/utils/rng/brg_endian.h, test/utils/rng/brg_sha1.c, test/utils/rng/brg_sha1.h, test/utils/rng/brg_types.h, test/utils/rng/rng.h, test/utils/rng/rng_brg.c, test/utils/rng/rng_brg.h
Depends on both https://github.com/sandialabs/qthreads/pull/181 and https://github.com/sandialabs/qthreads/pull/170. I'll revise it to not depend on those if that ends up being possible after debugging.
=> Fix Undefined Behavior Sanitizer Errors

test/basics/qthread_timer_wait.c
=> Atomic Updates For `qthread_timer_wait`

test/basics/qthread_cas.c
Use explicit atomics in `qthread_cas` instead of relying on x86-specific guarantees for loads and stores. Fixes #195.
=> Fix Race Condition In CAS Test

include/qt_qthread_struct.h, src/qthread.c
=> Atomics For Context Pointers

src/io.c
WIP. Hopefully will fix #196, but this patch appears to exchange a deadlock for the race condition instead. Opening this PR so CI can run and I can maybe get more info about what's going on.
=> Explicit Atomics For IO

src/mpool.c
=> Atomics For Memory Pool

.circleci/config.yml, .github/workflows/CI.yml
This is a minor CI improvement, but it does depend on #182.
=> Have Address Sanitizer Check Init Order In CI

include/qt_shepherd_innards.h, src/qthread.c, src/shepherds.c
=> Explicit Atomics For Shepherd And Worker Active Fields

.github/workflows/CI.yml, test/basics/qthread_stackleft.c, test/basics/sinc_workers.c
This is a mitigation for https://github.com/sandialabs/qthreads/issues/219. Unfortunately it's not a complete fix, but it does seem to at least prevent that issue from showing up on x86-64.
=> Adjust Stack And Test Problem Sizes

include/qt_atomics.h, src/threadqueues/nemesis_threadqueues.c
Depends on #185 and (transitively) #182.
=> Resolve Race Condition in Nemesis Threadqueue (#187)

include/qloop_innards.h, src/qloop.c, test/features/qt_loop.c
WIP. Currently a partial fix for #236.
=> Atomics In `qloop` Implementation

include/qt_io.h, include/qt_qthread_struct.h, src/feb.c, src/qthread.c, src/queue.c, src/syncvar.c, src/syscalls/accept.c, src/syscalls/connect.c, src/syscalls/poll.c, src/syscalls/pread.c, src/syscalls/pwrite.c, src/syscalls/read.c, src/syscalls/select.c, src/syscalls/system.c, src/syscalls/user_defined.c, src/syscalls/wait4.c, src/syscalls/write.c, src/threadqueues/distrib_threadqueues.c, src/threadqueues/sherwood_threadqueues.c, test/basics/arbitrary_blocking_operation.c
=> Use Explicit Atomics In Distrib Threadqueue

include/qt_atomics.h
Some of the errors I was seeing in #244 and #245 came from this, but it doesn't have its own standalone issue.
=> Fix Non-Atomic Load In Trylock

.cirrus.yml, .github/workflows/CI.yml
These often hang (I think for similar reasons as described in https://github.com/sandialabs/qthreads/issues/267#issuecomment-2423163776). They also always take a long time to run so I'm dropping them.
=> Reduce Cirrus CI ARM Builds

include/qt_spawncache.h, src/qthread.c, src/threadqueues/sherwood_threadqueues.c
This is an experimental PR that provides an alternate fix for https://github.com/sandialabs/qthreads/issues/324.
=> Atomic Queuelengths

CMakeLists.txt, src/CMakeLists.txt
=> Support Older CMake Versions

.circleci/config.yml
Fixes https://github.com/sandialabs/qthreads/issues/344
=> Fix CircleCI Permissions Issues

test/basics/qthread_readstate.c
I'm hoping (optimistically) that this fixes #342. It'll probably take a long while to confirm though since the hang is so intermittent. This PR certainly fixes a valid bug either way though since the old version of this test was a data race as-written.
=> Atomics For Spinning Waiter in qthread_readstate Test
