sandialabs/qthreads

- src/qalloc.c
- test/basics/hello_world_multi.c
- test/basics/qtimer.c
- test/basics/queue.c
I found several minor bugs while playing with the code base and valgrind. Most of these are extremely minor and were just used to remove warnings, etc. However, please pay special attention to 7860a17a335db7cd4bf176137bf6882ca1bbe7f3.
That path through the code allowed for that memory to never be released. I believe this corrects that the issue.
> Bugs valgrind

- include/qt_addrstat.h
- include/qt_blocking_structs.h
- include/qthread/qthread.h
- src/feb.c
- test/basics/Makefile.am
- test/basics/aligned_writeFF_basic.c
- test/basics/aligned_writeFF_waits.c
This adds support for writeFF on aligned (but not syncvar_t) FEB vars
In order to support writeFF I basically:
- added a new FEB queue called FFWQ (full full writers (aka writeFF) queue)
- cloned readFF to writeFF since the hash locking/unlocking and when we can
read/write is similar
- updated writeFF to
- use a WRITEFF blocker_type
- use dest instead of src for lockbin, alignedaddr, and x->addr
- use FFWQ instead of FFQ
Note that when an empty FEB is filled, the current implemenation performs all
writeFF operations first, and then continues onto the existing readFF
operations.
This also adds some writeFF tests to check that:
- writeFF on a full var writes, and leaves the FEB full
- concurrent writeFFs work without tearing
- writeFF on an empty var blocks until filled, then writes, and …
> Add aligned writeff

- include/qthread/qthread.h
- src/feb.c
- test/basics/Makefile.am
- test/basics/aligned_writeE_basic.c
- test/basics/aligned_writeE_wakes.c
This adds support for writeE on aligned (but not syncvar_t) FEB vars
In order to support writeE I basically cloned qthread_empty since the hash
locking/unlocking is the same, and added a write after the locking logic.
This also adds some writeE tests to check that:
- writeE on a full var writes, and empties the FEB
- writeE on an empty var writes, and leaves the FEB empty
- writeE on a full var wakes a blocked writeEF
> Add aligned writeE

- src/syscalls/nanosleep.c
- src/syscalls/sleep.c
- src/syscalls/usleep.c
They were being leaked previously, so destroy them before returning
> Destroy qtimer_t in sleep, usleep, and nanosleep

- include/qthread/qthread.h
- src/feb.c
- test/basics/Makefile.am
- test/basics/aligned_readXX_basic.c
This adds support for readXX on aligned (but not syncvar_t) FEB vars
qthread_readXX is really just a simple wrapper around:
```c
if (dest && (dest != src)) {
*(aligned_t *)dest = *(aligned_t *)src;
}
```
> Add aligned readXX

- test/basics/aligned_readXX_basic.c
- test/basics/aligned_writeE_basic.c
- test/basics/aligned_writeE_wakes.c
- test/basics/aligned_writeFF_basic.c
- test/basics/aligned_writeFF_waits.c
Whoops, not all compilers have an implicit "return 0" if the end of main is
reached. These tests were failing with some versions of pgi because of this.
> Make sure main() explicitly returns 0 in recently added FEB tests

- src/Makefile.am
- src/alloc/chapel.c
- src/qthread.c
- Add individual allocators to EXTRA_DIST to avoid .deps in release tarball
- Bring in qthread-int.h for uint_fast16_t in chapel.c
- Quiet qthread_tos()/qthread_bos() visibility warning. See #50 for more info
Individual commits have more detail
> Fix a few issues uncovered during full Chapel testing of qthreads 1.12

- include/qthread/qthread.hpp
This fixes a warning encountered in Chapel, which is turned into an error when \-Werror is used.
Qthreads has a clever implementation of `static_assert()` called `QTHREAD_STATIC_ASSERT()` that works even with older versions of the C\+\+ standard.  Unfortunately, the stricter checking performed by gcc 7.1 causes `QTHREAD_STATIC_ASSERT()` to provoke a warning that attributes are being ignored in a template argument.
The fix proposed here is to use the standard `static_assert()` when it is available (i.e. when using C\+\+11 or later).
@ronawho suggested that I submit this as a Qthreads PR since it has been implemented in Chapel's copy of Qthreads.
> Fix ignored attributes warning

- src/mpool.c
Ensure that we can store at least 2 items per pool (missed in
https://github.com/chapel-lang/chapel/commit/93869777321 / https://github.com/Qthreads/qthreads/commit/5dc11401)
Partial cherry-pick of https://github.com/chapel-lang/chapel/commit/de54d106d1
> Fix a bug in pool limiting code

- configure.ac
- src/Makefile.am
- src/affinity/hwloc_via_chapel.c
Add a Qthreads affinity shim called "hwloc_via_chapel", which is
identical to the existing "hwloc" except that it attempts to get the
hwloc topology from the Chapel runtime before getting it from hwloc
directly.
This allows Chapel to initialize a hwloc topology on our end just
pass that off to qthreads, instead of having qthreads reload the
topology. This ensures that chapel/qthreads have the same topology
and prevents double loading the topology, which is slow (#41)
Partial cherry-pick of https://github.com/chapel-lang/chapel/pull/9824
> Add chapel hwloc layer

- src/alloc/chapel.c
We have arranged for Qthreads to get memory from Chapel memory layer
rather than the regular malloc() interface.  But we've been using the
internal memory-layer-specific functions (chpl_malloc() for example)
rather than the public functions (chpl_mem_alloc() for example) that
report out-of-memory conditions and support tracking.  Here, switch
Qthreads' usage to the latter.  This will allow us to get the usual
Chapel "Out of memory allocating <something>" message when the Qthreads
tasking layer asks for memory and the runtime can't supply it.
This modifies the Qthreads src/alloc/chapel.c memory interface to use
the public memory interface instead of the internal one.
Partial cherry-pick of https://github.com/chapel-lang/chapel/commit/0c3b9de163
> Use Chapel's public memory interface instead of the internal one

- include/qt_atomics.h
- include/qt_int_log.h
- include/qthread/loop_iter.hpp
- include/qthread/qthread.h
- src/ds/dictionary/hash.c
- src/performance.c
- src/qloop.c
- src/qutil.c
- src/syncvar.c
The `register` keyword is deprecated in C++, and some compilers are starting to issue warnings when they see it.  This can cause problems for projects that use `-Werror` because the build aborts upon seeing the warnings.
Chapel is one such project.  In the Chapel runtime, `qthread.h` is included from both C and C++ code, and the C++ code now aborts when compiling for a target such as IA32, for which `qthread.h` contains `register` declarations.
For consistency, this PR removes the `register` keyword everywhere, not just in `qthread.h`.  We'd appreciate it if this PR or something equivalent could be merged.
@gbtitus , @ronawho - FYI.
> Remove deprecated register keyword

- include/qthread/Makefile.am
- include/qthread/allpairs.h
- include/qthread/barrier.h
- include/qthread/cacheline.h
- include/qthread/dictionary.h
- include/qthread/hash.h
- include/qthread/io.h
- include/qthread/omp_defines.h
- include/qthread/qarray.h
- include/qthread/qdqueue.h
- include/qthread/qlfqueue.h
- include/qthread/qloop.h
- include/qthread/qloop.hpp
- include/qthread/qpool.h
- include/qthread/qswsrqueue.h
- include/qthread/qt_syscalls.h
- include/qthread/qthread.h
- include/qthread/qthread.hpp
- include/qthread/qtimer.h
- include/qthread/qutil.h
- include/qthread/sinc.h
- include/qthread/spr.h
- include/qthread/syncvar.hpp
- include/qthread/top/qthread.h
- include/qthread/wavefront.h
This PR addresses #70 
Public headers (e.g., `qthread.h`) writes `#include <qthread/xxx.h>` to include other Qthreads headers.  The compiler only looks up global include paths, so a compiler cannot find headers if the Qthreads' include path (`QTHREAD_INSTALL_DIR/include`) is not added to its global include paths.  This patch fixes it by using relative paths (`#include "xxx.h"`).
Note that this change does not break the existing program that includes Qthreads by `#include<qthread.h>` or `#include <qthread/qthread.h>`.
> Use relative paths to include Qthreads headers in public headers

- src/affinity/binders.c
- src/affinity/hwloc_v2.c
- src/affinity/hwloc_via_chapel.c
Updates affinity support through hwloc_v2, binders and hwloc_via_chapel to more recent hwloc APIs:
- Fixes compilation errors for hwloc2.x. 
- Maintains backward compatibility to >=hwloc1.5. 
- Uses hwloc2.x fallback where hwloc_get_type_depth(NUMANode) results in a negative int as NUMA nodes are not in the object tree anymore. This is documented [here](https://www.open-mpi.org/projects/hwloc/doc/v2.0.4/a00327.php), section "NUMA level and depth".
> Fix compilation errors for hwloc_v2, binders and hwloc_via_chapel when using hwloc2.x

- .github/workflows/CI.yml
Use Github Actions to enable CI testing. Run `make check` for linux64
with the `sherwood` and `nemesis` schedulers as well with the `hwloc`
and `no` topologies.
This also adds a mac build, but `make check` currently hangs so it's
just building and not running any tests.
> Add github actions CI testing

- config/qthread_check_bitfield_order.m4
- config/qthread_check_qsort.m4
Add signal handling for two conftests in order to avoid segmentation error pop-ups on some platforms when configuring the project.
> Conftest handlesignal qsort

- config/qthread_check_hwloc.m4
Add a --with-hwloc-symbol-prefix argument to configure that specifiesthe prefix for hwloc
symbols in the case that hwloc was also configured with the --with-hwloc-symbol-prefix argument.
This allows configure to find the hwloc library by searching for a hwloc symbol with the
proper prefix. The default value of this argument is "hwloc_".
> Support for a custom hwloc symbol prefix

- src/compat_atomics.c
- src/qthread.c
Fixes failing compilation when QThreads configured with certain options.
> Add missing header

- config/qthread_check_swapcontext.m4
- src/fastcontext/asm.S
Removes case block in m4 file. This allows to use ucontext on Macs and removes the requirement to use fast context on all Macs. Using fast context is current unsupported on M1 Macs. This resolves the compilation error.
> Mac allow system ucontext

- include/qt_atomics.h
- test/stress/Makefile.am
- test/stress/lock_acq_rel.c
Adds the atomic type specifier (C11) to members of structs used for thread synchronization. This implements sequential consistency (memory_order_seq_cst) for loads and stores to these members. This PR should fix issues on weakly-ordered systems (ARM, PowerPC) as described here:
- Sinc issues with multiple workers per shepherd on power and arm [#57]
> Fix memory consistency issues on PowerPC and ARM

- config/qthread_check_assembly.m4
Lassen at LLNL reports `host='powerpc64le-unknown-linux-gnu'` thus the m4 script does not detect the architecture correctly.
> Detect Power9 during configure of asm inline support on Lassen

- src/io.c
./test/basics/arbitrary_blocking_operation hangs in qt_blocking_subsystem_internal_stopwork on ARM here:
https://github.com/Qthreads/qthreads/blob/71d29efea190c7cd1349be9b4feb0d5047f92132/src/io.c#L65
It seems that the counter decrement happens in an incorrect conditional branch as the following condition is not always true and thus the decrement never occurs. In that case, the code above spins forever and `qthread_internal_cleanup_early` and qthread_finalize never finish.
https://github.com/Qthreads/qthreads/blob/71d29efea190c7cd1349be9b4feb0d5047f92132/src/io.c#L132
> Fix io proxy exit condition check

- configure.ac
Proposing to increase the default stack size to 16kB. This allows to use larger stack local variable types and would improve support of many use-cases that segfault otherwise.
> Increase default stack size from 4kB to 16kB

- src/fastcontext/asm.S
This makes Qthreads compile with fast context switching implemented in asm.
> Enable QTHREAD_ARMV8_A64 context swap on Apple Mx (ARM) hardware

- include/qt_hash.h
- include/qthread/qthread.h
- src/hashmap.c
- src/locks.c
- src/qthread.c
- test/stress/lock_acq_rel.c
This is another implementation using hashmaps of spinlocks and likely the way to go. Needs a bit of work
With this infrastructure, we should be able to support ULTs from Open MPI.
For Open MPI, we'd need then these changes:
https://github.com/janciesko/ompi/commit/daef600cee3ed9607f10829c5dc3b4de5da0bc4c
https://github.com/janciesko/ompi/commit/bab853bf53355c6fbe71f24a4321bf19293d1165
>  [WIP] Add support for recursive locks and try_lock (using spinlocks)

- include/qt_atomics.h
- include/qthread/qthread.h
- src/locks.c
- src/qthread.c
This adds support for locking with external lock allocations. In this case, the external lock must be a qthread_spinlock_t thus the API has the name `spinlock` to disambiguate. This covers the use-case coming from ompi where ompi provides the lock.
> Add support for recursive locks with external lock allocation

- test/basics/qthread_stackleft.c
-O2 seems to override Q_NOINLINE thus inner recursions would not advance stack ptr. A return value enforces this. 
I have uncommented the commented section which now works.
> Add return value in inner function in stackleft unit test

- src/fastcontext/context.c
@cjhackillinois - you had this change in  mind?
`make check` passes on ARM64.
> Make stack size in number of word-size entries for ARM64

- test/basics/Makefile.am
- test/basics/qthread_timer_wait.c
Adds the mentioned reproducer as unit test. This test is different to test/basics/qtimer.c as it tests ordering behavior of tasks when using timer.
> Add unit test for qthread timer testing for correct task ordering

- include/fastcontext/arm-ucontext.h
- src/fastcontext/asm.S
This addresses issue #123 by storing/loading FPU registers in the arm64 fastcontext.
> FPU store/load for arm64 fastcontext

- config/qthread_check_hwloc.m4
I botched my last PR #131, it didn't set `CPPFLAGS` and `LDFLAGS` properly if `hwloc` link checks were disabled. I think I forgot to run `autoreconf` at some point during testing so I was testing against an out-of-date `configure` script.
> Fix --disable-hwloc-configure-checks behavior

- config/qthread_ia_cacheline.m4
- include/qthread/common.h.in
This adds the definition of QTHREAD_ARM so it would not resolve to the same as QTHREAD_UNSUPPORTED in scenarios such as as `#if (QTHREAD_ASSEMBLY_ARCH == QTHREAD_ARM)`. 
This also updates definitions in the cacheline conf m4. 
```
/* Architecture defines */
#define QTHREAD_UNSUPPORTED 0
#define QTHREAD_IA32        1
#define QTHREAD_AMD64       2
#define QTHREAD_IA64        3
#define QTHREAD_ALPHA       4
#define QTHREAD_MIPS        5
#define QTHREAD_POWERPC32   6
#define QTHREAD_POWERPC64   7
#define QTHREAD_SPARCV9_32  8
#define QTHREAD_SPARCV9_64  9
#define QTHREAD_TILEPRO	    10
#define QTHREAD_TILEGX	    11
#define QTHREAD_ARM         12
#define QTHREAD_ARMV8_A64   13
```
> Define QTHREAD_ARM and include defines in config test

- test/basics/Makefile.am
- test/basics/qthread_fp.c
- test/basics/qthread_fp_double.c
> Add code to test double values with vector regs

- include/qthread/qthread.h
- src/qthread.c
Add `qthread_reset_target_shep()`, which resets the shepherd that tasks created with `NO_SHEPHERD` get spawned to. This is useful in Chapel for cases where we want to use the default spawn location, but get good NUMA affinity between data parallel loops sepreated by some other task spawn.
Just using the `qthread_fork_to` API would disable future stealing, so this is a mechanism  to get tasks in consecutive data parallel loops to spawn to the same shepherds without preventing stealing.
This was originally done in chapel-lang/chapel#12868, which includes some perf results. At the time I expected we'd update our shim to use `qthread_fork_to`, but had not considered the work-stealing implications at the time.
> Add a mechanism to reset the default task spawn order

- test/basics/.gitignore
- test/stress/.gitignore
This adds some additional build artifacts to the .gitignore. In particular it helps me get a clean build environment via `git clean -fdX` (note the capital X which only clears away ignored files).
> Add test binaries to .gitignore.

- .github/workflows/CI.yml
Depends on https://github.com/sandialabs/qthreads/pull/141
> WIP: Expand CI Configs

- .github/workflows/CI.yml
This fixes a minor bug in https://github.com/sandialabs/qthreads/pull/171 where there was still a lingering clang-17 build getting generated by the main clang-on-linux matrix.
> Typo in Clang CI Build Matrix

- .circleci/config.yml
Trying CircleCI's ARM workers since CirrusCI's ARM queue is extremely backlogged.
> WIP: Test CircleCI for ARM Builds

- .cirrus.yml
Experimenting with Cirrus CI since it seems to be an easy way to get builds on both Arm and Mac M1.
> Experimenting With Cirrus CI

- .github/workflows/CI.yml
Needed for https://github.com/sandialabs/qthreads/pull/176. Apparently when stackleft succeeds in CI it runs into a typo later on in my CI config for clang.
> Fix Typo In clang GH Actions CI

- test/basics/qthread_fp.c
- test/basics/qthread_fp_double.c
If a compiler is optimizing overly aggressively it may make assumptions about commutativity/associativity of floating point numbers that don't actually hold perfectly in practice. That's a likely cause of the current test failure with icx. The result in the test is just slightly off from the expected value. While this could arguably be a bug upstream, it's generally a bad idea to use exact float equality for tests. Relative error is a more reliable measure. This change makes the float-related tests check relative error rather than actual equality. The thresholds are very conservative, but checking this way should insulate our test suite from failures resulting in small differences in floating point handling at the compiler and/or hardware level.
> Relative Error Checking for Floating Point Tests. Fixes #172.

- .clang-format
I'd like to start using clang-format to manage formatting. As far as I can tell, the formatting isn't especially consistent across the codebase right now. Here's an initial config based on my own preferences that we can use as a starting point. Feel free to suggest any changes.
I'll leave this open for a while to give time for any comments. Once we've settled on a format spec to use, I'll set things up to exclude any vendored files, apply the format to the whole codebase whenever there aren't open pull requests, then set up a CI build to check that the formatting has been correctly applied to each pull request.
> Proposed clang-format Config

- src/hashmap.c
Fixes #193.
The hashmap code isn't necessarily optimal, but this PR brings the code into agreement with what's already happening on x86 by avoiding implicit race conditions. It also gives us a minimum working version to iterate off of later.
> Explicit Atomics In Hashmap

- src/lf_hashmap.c
Similar to other recent pulls, avoid relying on the x86 guarantees about memory consistency and instead use explicit atomic instructions.
Fixes #217.
> Explicit Atomics in lf_hashmap

- test/basics/aligned_writeFF_basic.c
This is an alternative to https://github.com/sandialabs/qthreads/pull/221.
> Skip Concurrent WriteFF Test When Thread Sanitizer Is Enabled

- include/qthread/qthread.h
Note: I think these functions should be totally rewritten using C11 atomics later (see #225), but this is just a minimal fix for #224.
> Explicit Atomics For Incr Fallback Implementations

- include/qt_addrstat.h
- include/qt_atomics.h
- src/hashmap.c
- src/mpool.c
> Use Explicit Atomics In The Internal Spinlock

- src/fastcontext/context.c
Fixes #219.
Something about thread sanitizer's instrumentation doesn't like our context swap implementation. As documented in #219 there's a segfault during cleanup that happens because in some cases a worker thread fails to return from swapping the context to a qthread. This particular function isn't a source of concern for race conditions anyway so I'm just turning the sanitizer off locally.
> Disable Thread Sanitizer Instrumentation for Context Swap

- src/syncvar.c
This one's more straightforward than the debate around `aligned_t` because syncvars were already treated as atomics internally. This was just a matter of making the loads and stores explicit.
I also made ARM take the same branch as x86 for these blocks of code since we're currently assuming lock-free atomics there too.
> Explicit Atomics in Syncvar Implementation

- test/features/qarray.c
WIP. Will eventually fix #240.
> Qarray Race Condition Fixes

- src/qthread.c
- test/basics/qthread_stackleft.c
The intermittent failure with thread sanitizer can be eliminated by just getting rid of a little bit of the instrumentation (similar to #231). Given the slight incompatibility I already saw in #231 and the fact that this is not at all an invasive change I'm inclined to call this good enough.
While working on stackleft I also changed it to use `__builtin_frame_address(0)` instead of taking the address of a local variable to estimate the stack pointer since that seems like it'll be more reliable in the long run.
> Fix Intermittent Stackleft Crash With Thread Sanitizer

- configure.ac
I've had to do this enough times while debugging that I'm proposing we just update the default. For some reason it seems to matter more on ARM systems, though I'm not sure why.
> Increase Default Stack Size

- test/basics/aligned_writeFF_basic.c
- test/stress/lock_acq_rel.c
This prevents these tests from taking so long in CI.
> Adjust Test Problem Sizes

- src/feb.c
- test/basics/hello_world.c
Careful review appreciated for this one in particular.
This changes the implementation of FEBs so that a memory fence occurs even when the output value passed to the FEB routine is null. This matters because prior to this change, there's not necessarily a guaranteed fence implied by calls like `readFF` and the tests frequently use `readFF` to decide that it's safe to read some value that may be completely distinct from the FEB that's been marked as full.
> Adjust FEB Fences

- src/feb.c
- src/syncvar.c
Fixes #202.
As best I can tell, this function is only ever called in one place and the lock is managed by the caller there, so no unlock is needed. It's probably a leftover typo from some previous refactoring.
> Fix Syncvar and FEB Lock/Unlock In Different Threads

- .cirrus.yml
The old image we were using is no longer available and there's a new one out now, so we're updating to testing on freebsd 14.
> Update to latest available freebsd image in CI.

- README.md
- config/ax_c_restrict.m4
- config/ax_openmp.m4
- config/qthread_check_assembly.m4
- config/qthread_check_atomics.m4
- config/qthread_check_attributes.m4
- config/qthread_detect_compiler_type.m4
- config/qthread_ia_cacheline.m4
- configure.ac
- include/qt_atomics.h
- include/qthread/common.h.in
- include/qthread/qthread.h
- include/qthread_innards.h
- src/cacheline.c
- src/compat_atomics.c
- src/ds/qarray.c
- src/fastcontext/asm.S
- src/qthread.c
- src/syncvar.c
- src/threadqueues/sherwood_threadqueues.c
- test/argparsing.h
Note! This depends on https://github.com/sandialabs/qthreads/pull/273 to avoid merge conflicts.
> Drop Support for Old/Broken Compilers

- include/qt_qthread_struct.h
- include/qthread_innards.h
- src/qthread.c
This adds the API calls needed to help the thread sanitizer correctly carry its happens-before relationships across context swaps.
> Thread Sanitizer Interop

- .github/workflows/CI.yml
Use actions checkout v4 to avoid warning about deprected version of node.js.
> Update Actions Checkout Version

- src/fastcontext/context.c
I conduct automated regression testing of Chapel using GASNet-EX for multi-locale support on a variety of systems.
Recently my testing on big-endian PPC64/Linux began failing (SEGV early in startup).
Based on the last-good/first-bad test dates, Brad Chamberlain identified Chapel's update of Qthreads from 1.20 to 1.21 as a likely cause. 
I have confirmed that if I build the 1.21 release of Qthreads on a big-endian PPC64 it fails in `make check`, with a SEGV in nearly every test.  However, `make check` passes fine with the 1.20 release.
This single-commit PR is necessary and sufficient to allow the `hello_world` test (among others) to PASS.  
However, this is not sufficient to get a clean run of `make check`.
I, unfortunately, cannot devote additional time to addressing whatever else is …
> Restore fastcontext support for big-endian PPC64

- include/qt_atomics.h
This fixes a performance regression in release 1.21 that's impacting some benchmarks downstream in Chapel.
> Fix performance regression in Qthreads 1.21

- include/qt_atomics.h
- include/qthread/qthread.h
- src/hashmap.c
- src/io.c
These are some minor performance fixes to help fix regressions downstream
In particular, this removes an unnecessary thread fence in the IO code, and updates the MACHINE_FENCE macro to use a stronger type of memory fence (since this somehow results in better performance in practice).
The trylock patch is just a simplification that I wrote while attempting to debug the performance regressions. That should be performance neutral.
> Minor Performance Regression Fixes

- include/qthread/qthread.h
This reverts one of the commits from #314 since it ended up being more harmful than helpful downstream. The Chapel array init/deinit benchmark seems to be very hardware dependent and we don't want to eliminate the big improvements in other applications from the 1.21 release.
> Additional Performance Fixes

- CMakeLists.txt
- configure.ac
- src/CMakeLists.txt
- src/fastcontext/asm.S
- src/io.c
- src/syscalls/accept.c
- src/syscalls/connect.c
- src/syscalls/poll.c
- src/syscalls/pread.c
- src/syscalls/pwrite.c
- src/syscalls/read.c
- src/syscalls/select.c
- src/syscalls/system.c
- src/syscalls/user_defined.c
- src/syscalls/wait4.c
- src/syscalls/write.c
Now that the dramatic configure simplifications from the last release are done, this is possible. At the moment it's a very skeletal  build that only covers building the main library, but I'll expand it to include tests and more options soon. This is just the minimum working version.
> Allow Building Using CMake

- src/CMakeLists.txt
- src/cacheline.c
- src/ds/dictionary/dictionary_shavit.c
- src/ds/dictionary/dictionary_simple.c
- src/ds/dictionary/dictionary_trie.c
- src/ds/qarray.c
- src/ds/qdqueue.c
- src/ds/qlfqueue.c
- src/ds/qpool.c
- src/ds/qswsrqueue.c
- src/patterns/allpairs.c
- src/qalloc.c
- src/qloop.c
- src/qtimer/gethrtime.c
- src/qtimer/gettime.c
- src/qtimer/gettimeofday.c
- src/qtimer/mach.c
- src/syncvar.c
- src/syscalls/user_defined.c
Fixes https://github.com/sandialabs/qthreads/issues/165.
I figured I'd clear this away while setting up the new CMake build. I'm leaving the autotools one as-is since getting that configured in a compiler-independent way is more of a bother.
> Default to Hidden Symbol Visibility

- CMakeLists.txt
The previous value was just a placeholder. This is what the actual requirement is. It's required specifically because we use the FILE_SET argument to the `install(TARGET ...)` command to simplify the installation code. We can add compatibility with older versions later if there's some compelling reason to do so.
> Realistic CMake Minimum version

- .github/workflows/CI.yml
- README.md
The new OSX/gcc CI config is actually just picking up an alias to appleclang. This fixes that.
Also included: a minor documentation fix.
> Ensure OSX CI Picks Up Gcc When Specified

- test/basics/queue.c
Fixes #324. Turns out the consistency check causing the error was another one that relies on internal (unreliable) estimates of queue states so it's not particularly suitable to be used as a unit test anyway.
> Skip Unreliable Consistency Check

- src/CMakeLists.txt
These options hadn't been ported over from the old autotools build and were actually used downstream. This adds them.
> Add CMake Options Needed By Chapel

- CMakeLists.txt
- cmake/Findhwloc.cmake
- src/CMakeLists.txt
There's a need downstream for being able to configure hwloc via the standard `_ROOT` mechanism as opposed to just supplying a hint since the hint can get unintentionally overridden by `CMAKE_MODULE_PATH`. This required setting up a find module for hwloc and then using find_package to find it instead, as is done here.
> Use `find_package` for Finding Hwloc in CMake

- src/affinity/binders.c
- src/affinity/hwloc.c
It wasn't getting routed through our CMake config back into the relevant places in the source files.
This bug caused a very minor performance regression in the launch downstream in chapel.
> Properly Route HWLOC_GET_TOPOLOGY_FUNCTION

- .circleci/config.yml
- include/qt_arithmetic.h
- include/qt_asserts.h
- include/qt_atomic_wait.h
- include/qt_branching.h
- include/qt_macros.h
- include/qt_os.h
- include/qt_threadpool.h
- src/CMakeLists.txt
- src/threadpool.c
- test/CMakeLists.txt
- test/internal/CMakeLists.txt
- test/internal/threadpool.c
Not connected to anything else yet.
> New Internal Threadpool Implementation

- src/CMakeLists.txt
Inspired by a bug on a "ppc64le" machine. It turned out that the old build system was using the fallback implementation on that platform which was hiding the fact that our context swap code doesn't actually work there. We're only nominally committed to supporting any kind of powerpc platform whatsoever so this just makes the new build system fall back to the system swapcontext on that platform. We may just fix the little-endian bug or just drop support for that platform later, but this at least maintains the baseline of working on that platform for now.
> Only Default To Fastcontext When It's Known To Work

- CMakeLists.txt
- qthread-config.cmake.in
- src/CMakeLists.txt
CMake needs some additional config files installed to make `find_package` work correctly.
> Fix Finding Qthreads Via find_package

- src/affinity/binders.c
Fixes a buffer overflow caused by an off-by-one error. See #365 for details
Resolves https://github.com/sandialabs/qthreads/issues/365
> Fix buffer overflow in binders.c

- src/CMakeLists.txt
> Add soname to shared library
